change schema
nf-core/proteinfold pull request #205
Opened 2024-10-25 15:36 UTC by luisas

Fixes #200 

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If necessary, also make a PR on the nf-core/proteinfold _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.

2024-10-25 15:47 UTC, luisas commented
this won't run until this is merged: https://github.com/nf-core/test-datasets/pull/1362

2024-10-28 09:47 UTC, JoseEspinosa requested changes
LGTM!
Please udpate the changelog and once tests pass we are ready to merge :rocket

2024-10-28 09:49 UTC, JoseEspinosa requested changes
LGTM!
Please udpate the changelog and once tests pass we will be ready to merge 🚀

2024-10-28 10:09 UTC, JoseEspinosa commented on CHANGELOG.md
> +- [[PR ##205](https://github.com/nf-core/proteinfold/pull/205)] - Change input schema from sequence,fasta to id,fasta.
```suggestion
- [[PR ##205](https://github.com/nf-core/proteinfold/pull/205)] - Change input schema from `sequence,fasta` to `id,fasta`.
```

2024-10-28 10:10 UTC, JoseEspinosa approved these changes
Awesome!

2024-10-28 10:28 UTC, merged