[WIP] Add RoseTTAFold-All-Atom
nf-core/proteinfold pull request #220
Opened 2024-11-20 05:19 UTC by jscgh

Adds RoseTTAFold-All-Atom as a module per https://github.com/nf-core/proteinfold/issues/197.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/proteinfold/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/proteinfold _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`). ## Tested with -profile test,singularity
- [x] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### To-Do
- [ ] Add db downloads to prepare_rosettafold_all_atom_dbs.nf
- [ ] Finish updating docs

2025-02-14 11:34 UTC, JoseEspinosa requested changes
Just left some minor suggestions but otherwise LGTM Awesome job @jscgh and @nbtm-sh! 🚀

2025-02-14 11:34 UTC, JoseEspinosa commented on modules/local/run_rosettafold_all_atom.nf
> +    path "versions.yml", emit: versions
```suggestion
    path ("${fasta.baseName}*")
    tuple val(meta), path ("${meta.id}_rosettafold_all_atom.pdb"), emit: top_ranked_pdb
    tuple val(meta), path ("*pdb")                               , emit: pdb
    tuple val(meta), path ("*_mqc.tsv")                          , emit: multiqc
    path "versions.yml"                                          , emit: versions
```

2025-02-14 11:34 UTC, JoseEspinosa commented on nextflow.config
> +        if (params.use_gpu) { apptainer.runOptions = '--nv' }
This will make the Nextflow language server happy
```suggestion
        params.use_gpu ? '--nv' : apptainer.runOptions
```

2025-02-14 11:34 UTC, JoseEspinosa commented on nextflow_schema.json
> -                    "default": false,
This is set to `false` by default isn't it? https://github.com/nf-core/proteinfold/blob/16fd7808df923e8fa6b352f3ced376af9e5b83cf/nextflow.config#L21
```suggestion
                    "default": false,
```

2025-02-14 11:34 UTC, JoseEspinosa commented on nextflow_schema.json
> +    ],
For consistency, maybe create a `rosettafold_all_all_atom_dbs_and_parameters_path_options` and a `rosettafold_all_all_atom_dbs_and_parameters_link_options` definitions, actually for modifying the schema you can use `nf-core pipelines schema build`, see [here](https://nf-co.re/docs/nf-core-tools/pipelines/schema), which provides a GUI in case it would be handy for you 😄

2025-02-14 11:34 UTC, JoseEspinosa commented on workflows/rosettafold_all_atom.nf
> +include { RUN_ROSETTAFOLD_ALL_ATOM      } from '../modules/local/run_rosettafold_all_atom'
```suggestion
include { RUN_ROSETTAFOLD_ALL_ATOM } from '../modules/local/run_rosettafold_all_atom'
```

2025-02-14 11:34 UTC, JoseEspinosa commented on workflows/rosettafold_all_atom.nf
> +    ch_versions       = ch_versions.mix(RUN_ROSETTAFOLD_ALL_ATOM.out.versions)
```suggestion
    ch_pdb      = ch_pdb.mix(RUN_ROSETTAFOLD_ALL_ATOM.out.pdb)
    ch_versions = ch_versions.mix(RUN_ROSETTAFOLD_ALL_ATOM.out.versions)
```

2025-02-18 02:22 UTC, jscgh commented on nextflow_schema.json
> +    ],
Done!

2025-02-18 21:56 UTC, JoseEspinosa reviewed
Tests are failing and seems there is an issue with the `nextflow.config` if you could take a look it would be great, otherwise I can do it tomorrow.

2025-02-19 09:53 UTC, JoseEspinosa reviewed
I tried to commit to the repository to fix the tests but I have not access to your repo, [this](https://github.com/nf-core/proteinfold/blob/d380ad4119f3d3d11680ac1f793b50caba9f389c/nextflow.config#L307-L314) lines need to be change by:
```
process.shell = [
    "bash",
    "-C",         // No clobber - prevent output redirection from overwriting files.
    "-e",         // Exit if a tool returns a non-zero status/exit code
    "-u",         // Treat unset variables and parameters as an error
    "-o pipefail" // Returns the status of the last command to exit with a non-zero status or zero if all successfully execute
]
```
To make nextflow edge happy

2025-02-19 10:33 UTC, jscgh commented
> I tried to commit to the repository to fix the tests but I have not access to your repo, [this](https://github.com/nf-core/proteinfold/blob/d380ad4119f3d3d11680ac1f793b50caba9f389c/nextflow.config#L307-L314) lines need to be change by:
> 
> ```
> process.shell = [
>     "bash",
>     "-C",         // No clobber - prevent output redirection from overwriting files.
>     "-e",         // Exit if a tool returns a non-zero status/exit code
>     "-u",         // Treat unset variables and parameters as an error
>     "-o pipefail" // Returns the status of the last command to exit with a non-zero status or zero if all successfully execute
> ]
> ```
> 
> To make nextflow edge happy

Thanks! Added the changes and gave you write access to the repo

2025-02-19 10:45 UTC, JoseEspinosa approved these changes
Thanks! Very nice job! 🚀

2025-02-19 10:45 UTC, merged