docker file for boltz
nf-core/proteinfold pull request #227
Opened 2024-12-04 03:54 UTC by ziadbkh

Adding a docker file to run boltz with ProteinFOld
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/proteinfold/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/proteinfold _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2025-02-18 21:58 UTC, JoseEspinosa reviewed
Just wanted to confirm that it is enough to install `boltz` from pip to create a working image with @nbtm-sh, before approving this PR, thanks!

2025-02-27 02:03 UTC, ziadbkh commented
It seems it is. It works on our internal HPC and used the GPU

2025-03-07 08:23 UTC, JoseEspinosa commented
No worries! Nice, anyway we won't merge this PR until the next release.

> @JoseEspinosa sorry for the long delay in reply, been super bogged down. the cuda libraries are listed as dependencies for boltz, so installing it with pip will be enough for it to play nice with 99% of HPC stuff.

2025-05-14 10:59 UTC, JoseEspinosa requested changes
Nice job! I dropped some suggestions 😄

2025-05-14 10:59 UTC, JoseEspinosa commented on main.nf
> +    ch_report_input.view()
```suggestion
```

2025-05-14 10:59 UTC, JoseEspinosa commented on modules/local/compare_structures/main.nf
> +    path (all_files)
Why adding the file names as a separate input and not keeping the previous version just providing the files

2025-05-14 11:57 UTC, ziadbkh commented on bin/generate_comparison_report.py
> +def align_structures_v1(structures):
we don't need it. I will delete it

2025-05-14 12:01 UTC, ziadbkh commented on nextflow.config
> +    test_full_boltz               { includeConfig 'conf/test_full_boltz.config'                        }
stub as stub = true in the test config?

2025-05-14 12:07 UTC, ziadbkh commented on modules/local/run_rosettafold_all_atom/main.nf
> +    path (files)
YAML or json that includes the information of the run...

2025-05-14 12:21 UTC, ziadbkh commented on modules/local/compare_structures/main.nf
> +    path (all_files)
this is needed when there is no msa or the msa is no_file as if multiple models have no_file, there will be file name collision. This way I stage all unique files and use the names as val for a list. Not sure if we can resolve it by using empty list instead of no_file
Hopefully, it makes sense

2025-05-14 12:24 UTC, ziadbkh commented on conf/test_helixfold3.config
> -stubRun = true
just for testing, forgot to put it back. I will.

2025-05-14 12:31 UTC, ziadbkh commented on conf/modules_boltz.config
> +    withName: 'BOLTZ_FASTA|MULTIFASTA_TO_CSV|SPLIT_MSA' {
how it will affect colabfold? I thought it would affect the three processes. and the three of them are very light. Unless you mean multifasta_to_csv for colabfold? I also think regardless of which model, these processes are very light. but also single_process label is not bad. I used it to push jobs in the cluster quickly. Happy to remove them and keep single_process

2025-05-15 09:32 UTC, JoseEspinosa approved these changes
Thanks @ziadbkh!
I would like to think a little bit more about how to stage those files on the processes in a more nf-core way but by the moment I think we can merge this one to keep working!

2025-05-15 09:32 UTC, JoseEspinosa commented on conf/test_full_boltz.config
> +stubRun = true
```suggestion
```

2025-05-15 09:49 UTC, merged